# Generated by Django 5.1.4 on 2025-09-17 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий к курсу', 'verbose_name_plural': '7. Комментарии к курсам'},
        ),
        migrations.AlterModelOptions(
            name='coursematerials',
            options={'ordering': ['order'], 'verbose_name': 'Материал курса (старый)', 'verbose_name_plural': '9. Материалы курсов (старые)'},
        ),
        migrations.AlterModelOptions(
            name='courseorderbyuser',
            options={'verbose_name': 'Запись на курс', 'verbose_name_plural': '6. Записи на курсы'},
        ),
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'Основная категория', 'verbose_name_plural': '1. Основные категории'},
        ),
        migrations.AlterModelOptions(
            name='replycomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Ответ на комментарий', 'verbose_name_plural': '8. Ответы на комментарии'},
        ),
        migrations.AlterModelOptions(
            name='sendverificationactivecourse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос на активацию курса', 'verbose_name_plural': '10. Запросы на активацию курсов'},
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название главы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание главы')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Глава курса',
                'verbose_name_plural': '4. Главы курсов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseChapterMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название материала')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание материала')),
                ('material_type', models.CharField(choices=[('video', 'Видео'), ('audio', 'Аудио'), ('document', 'Документ'), ('quiz', 'Тест'), ('assignment', 'Задание')], default='video', max_length=20, verbose_name='Тип материала')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='course_videos/', verbose_name='Видео файл')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='course_audio/', verbose_name='Аудио файл')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='course_documents/', verbose_name='Документ')),
                ('video_time', models.DurationField(blank=True, null=True, verbose_name='Длительность видео/аудио')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатный материал')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursechapter', verbose_name='Глава')),
            ],
            options={
                'verbose_name': 'Материал главы',
                'verbose_name_plural': '5. Материалы глав',
                'ordering': ['order'],
            },
        ),
    ]
