# Generated by Django 5.1.4 on 2025-09-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_coursecomment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseMaterials',
        ),
    ]
