# Generated by Django 5.1.4 on 2025-09-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_delete_coursematerials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replycomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Ответ на комментарий', 'verbose_name_plural': 'Ответы на комментарии'},
        ),
        migrations.AlterModelOptions(
            name='sendverificationactivecourse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос на активацию курса', 'verbose_name_plural': '8. Запросы на активацию курсов'},
        ),
        migrations.RemoveField(
            model_name='coursechaptermaterials',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='coursechaptermaterials',
            name='document_file',
        ),
        migrations.AlterField(
            model_name='coursechaptermaterials',
            name='material_type',
            field=models.CharField(choices=[('video', 'Видео'), ('quiz', 'Тест'), ('assignment', 'Задание')], default='video', max_length=20, verbose_name='Тип материала'),
        ),
        migrations.AlterField(
            model_name='coursechaptermaterials',
            name='video_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность видео'),
        ),
    ]
