# Generated by Django 5.2.6 on 2025-09-17 10:40

from django.db import migrations, models
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_replycomment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursechaptermaterials',
            name='material_type',
        ),
        migrations.AlterField(
            model_name='coursechaptermaterials',
            name='video_file',
            field=models.FileField(upload_to='course_videos/', verbose_name='Видео файл'),
        ),
        migrations.AlterField(
            model_name='coursechaptermaterials',
            name='video_time',
            field=models.DurationField(verbose_name='Длительность видео'),
        ),
    ]
