# Generated by Django 5.1.4 on 2025-09-17 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_coursechaptermaterials_material_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursechaptermaterials',
            name='video_time',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Длительность видео'),
        ),
    ]
