# Generated by Django 5.2.6 on 2025-09-18 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_coursechaptermaterials_video_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replycomment',
            name='comment',
        ),
        migrations.AlterUniqueTogether(
            name='courseorderbyuser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='courseorderbyuser',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseorderbyuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='replycomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sendverificationactivecourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='sendverificationactivecourse',
            name='user',
        ),
        migrations.AddField(
            model_name='courses',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CourseComment',
        ),
        migrations.DeleteModel(
            name='CourseOrderByUser',
        ),
        migrations.DeleteModel(
            name='ReplyComment',
        ),
        migrations.DeleteModel(
            name='SendVerificationActiveCourse',
        ),
    ]
