# Generated by Django 5.1.4 on 2025-09-18 06:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_replycomment_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursechaptermaterials',
            options={'ordering': ['order'], 'verbose_name': 'Материал главы', 'verbose_name_plural': '6. Материалы глав'},
        ),
        migrations.RemoveField(
            model_name='coursechaptermaterials',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='coursechaptermaterials',
            name='video_time',
        ),
        migrations.AddField(
            model_name='coursechaptermaterials',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/documents/', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='coursechaptermaterials',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='course_materials/images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='coursechaptermaterials',
            name='material_type',
            field=models.CharField(choices=[('document', 'Документ'), ('image', 'Изображение')], default='document', max_length=20, verbose_name='Тип материала'),
        ),
        migrations.CreateModel(
            name='CourseChapterVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название материала')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание материала')),
                ('video_file', models.FileField(upload_to='course_videos/', verbose_name='Видео файл')),
                ('video_time', models.DurationField(default=datetime.timedelta(0), verbose_name='Длительность видео')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатный материал')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursechapter', verbose_name='Глава')),
            ],
            options={
                'verbose_name': 'Материал главы',
                'verbose_name_plural': '5. Материалы глав',
                'ordering': ['order'],
            },
        ),
    ]
