# Generated by Django 5.1.4 on 2025-09-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_coursechaptermaterials_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursechaptervideo',
            options={'ordering': ['order'], 'verbose_name': 'Видео главы', 'verbose_name_plural': '5. Видео глав'},
        ),
    ]
