# Generated by Django 5.2.6 on 2025-09-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_coursereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], default=1, verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
