# Generated by Django 5.1.4 on 2025-09-19 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_coursereview_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание теста')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('passing_score', models.PositiveIntegerField(default=70, verbose_name='Проходной балл (%)')),
                ('time_limit', models.PositiveIntegerField(default=30, verbose_name='Время на прохождение (минуты)')),
                ('questions_count', models.PositiveIntegerField(default=10, verbose_name='Количество вопросов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Тест курса',
                'verbose_name_plural': '8. Тесты курсов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Балл')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Процент')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Пройден')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('answers', models.JSONField(default=dict, verbose_name='Ответы пользователя')),
                ('time_taken', models.PositiveIntegerField(default=0, verbose_name='Время прохождения (секунды)')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursequiz', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка прохождения теста',
                'verbose_name_plural': '10. Попытки прохождения тестов',
                'ordering': ['-started_at'],
                'unique_together': {('user', 'quiz')},
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('option_a', models.CharField(max_length=500, verbose_name='Вариант A')),
                ('option_b', models.CharField(max_length=500, verbose_name='Вариант B')),
                ('option_c', models.CharField(max_length=500, verbose_name='Вариант C')),
                ('option_d', models.CharField(max_length=500, verbose_name='Вариант D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Правильный ответ')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Объяснение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursequiz', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': '9. Вопросы тестов',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='Номер сертификата')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.quizattempt', verbose_name='Попытка')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursequiz', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сертификат теста',
                'verbose_name_plural': '11. Сертификаты тестов',
                'ordering': ['-issued_at'],
                'unique_together': {('user', 'quiz')},
            },
        ),
    ]
