# Generated by Django 5.1.4 on 2025-09-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_coursequiz_quizattempt_quizquestion_quizcertificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursequiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Тест курса', 'verbose_name_plural': 'Тесты курсов'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Попытка прохождения теста', 'verbose_name_plural': 'Попытки прохождения тестов'},
        ),
        migrations.AlterModelOptions(
            name='quizcertificate',
            options={'ordering': ['-issued_at'], 'verbose_name': 'Сертификат теста', 'verbose_name_plural': 'Сертификаты тестов'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['created_at'], 'verbose_name': 'Вопрос теста', 'verbose_name_plural': 'Вопросы тестов'},
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together=set(),
        ),
    ]
