# Generated by Django 5.2.6 on 2025-09-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_coursequiz_options_alter_quizattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': '01. Категории'},
        ),
        migrations.AlterModelOptions(
            name='coursechapter',
            options={'ordering': ['order'], 'verbose_name': 'Глава курса', 'verbose_name_plural': '04. Главы курсов'},
        ),
        migrations.AlterModelOptions(
            name='coursechaptermaterials',
            options={'ordering': ['order'], 'verbose_name': 'Материал главы', 'verbose_name_plural': '06. Материалы глав'},
        ),
        migrations.AlterModelOptions(
            name='coursechaptervideo',
            options={'ordering': ['order'], 'verbose_name': 'Видео главы', 'verbose_name_plural': '05. Видео глав'},
        ),
        migrations.AlterModelOptions(
            name='coursequiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Тест курса', 'verbose_name_plural': '08. Тесты курсов'},
        ),
        migrations.AlterModelOptions(
            name='coursereview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв о курсе', 'verbose_name_plural': '07. Отзывы о курсах'},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['-created_at'], 'verbose_name': 'Курс', 'verbose_name_plural': '03. Курсы'},
        ),
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'Основная категория', 'verbose_name_plural': '01. Основные категории'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Попытка прохождения теста', 'verbose_name_plural': '10. Попытки прохождения тестов'},
        ),
        migrations.AlterModelOptions(
            name='quizcertificate',
            options={'ordering': ['-issued_at'], 'verbose_name': 'Сертификат теста', 'verbose_name_plural': '11. Сертификаты тестов'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['created_at'], 'verbose_name': 'Вопрос теста', 'verbose_name_plural': '09. Вопросы тестов'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': '02. Подкатегории'},
        ),
    ]
