# Generated by Django 5.1.4 on 2025-09-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_categories_options_alter_coursechapter_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_d',
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='Правильный ответ'),
        ),
    ]
