# Generated by Django 5.1.4 on 2025-09-18 15:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0010_alter_coursechaptervideo_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный заказ')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Заказ выполнен')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ курса',
                'verbose_name_plural': '1. Заказы курсов',
                'ordering': ['-order_date'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseChapterForOrderedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название главы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание главы')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Активна')),
                ('chapter_order', models.PositiveIntegerField(default=0, verbose_name='Порядок главы')),
                ('is_accessible', models.BooleanField(default=True, verbose_name='Доступна')),
                ('access_granted_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата предоставления доступа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.courseorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Глава для заказанного пользователя',
                'verbose_name_plural': '2. Главы для заказанных пользователей',
                'ordering': ['chapter_order'],
                'unique_together': {('order', 'title')},
            },
        ),
        migrations.CreateModel(
            name='CourseMaterialForOrderedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название материала')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание материала')),
                ('material_type', models.CharField(choices=[('document', 'Документ'), ('image', 'Изображение')], default='document', max_length=20, verbose_name='Тип материала')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='course_materials/ordered/images/', verbose_name='Изображение')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='course_materials/ordered/documents/', verbose_name='Документ')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатный материал')),
                ('material_order', models.PositiveIntegerField(default=0, verbose_name='Порядок материала')),
                ('is_accessible', models.BooleanField(default=True, verbose_name='Доступен')),
                ('access_granted_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата предоставления доступа')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.coursechapterforordereduser', verbose_name='Глава')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.courseorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Материал для заказанного пользователя',
                'verbose_name_plural': '4. Материалы для заказанных пользователей',
                'ordering': ['material_order'],
                'unique_together': {('order', 'title')},
            },
        ),
        migrations.CreateModel(
            name='CourseVideoForOrderedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название видео')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание видео')),
                ('video_file', models.FileField(upload_to='course_videos/ordered/', verbose_name='Видео файл')),
                ('video_time', models.DurationField(default=datetime.timedelta(0), verbose_name='Длительность видео')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатный материал')),
                ('video_order', models.PositiveIntegerField(default=0, verbose_name='Порядок видео')),
                ('is_accessible', models.BooleanField(default=True, verbose_name='Доступно')),
                ('access_granted_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата предоставления доступа')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.coursechapterforordereduser', verbose_name='Глава')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.courseorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Видео для заказанного пользователя',
                'verbose_name_plural': '3. Видео для заказанных пользователей',
                'ordering': ['video_order'],
                'unique_together': {('order', 'title')},
            },
        ),
    ]
