# Generated by Django 5.1.4 on 2025-09-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursechapterforordereduser',
            unique_together={('order', 'title', 'chapter_order')},
        ),
        migrations.AlterUniqueTogether(
            name='coursematerialforordereduser',
            unique_together={('order', 'title', 'material_order')},
        ),
        migrations.AlterUniqueTogether(
            name='coursevideoforordereduser',
            unique_together={('order', 'title', 'video_order')},
        ),
    ]
