# Generated by Django 5.1.4 on 2025-09-18 15:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_coursechapterforordereduser_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watched', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('watched_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('watch_duration', models.DurationField(default=datetime.timedelta(0), verbose_name='Время просмотра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.coursevideoforordereduser', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Прогресс просмотра видео',
                'verbose_name_plural': '5. Прогресс просмотра видео',
                'unique_together': {('user', 'video')},
            },
        ),
    ]
