# Generated by Django 5.1.4 on 2025-09-19 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_coursechaptervideo_options'),
        ('order', '0003_uservideoprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseorder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseorder',
            name='sender',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email отправителя'),
        ),
        migrations.AlterField(
            model_name='courseorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='courseorder',
            unique_together={('sender', 'course')},
        ),
    ]
