# Generated by Django 5.1.4 on 2025-09-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='FAQ savoli', max_length=500, verbose_name='Savol')),
                ('answer', models.TextField(help_text='FAQ javobi', verbose_name='Javob')),
                ('category', models.CharField(blank=True, help_text='FAQ kategoriyasi', max_length=100, null=True, verbose_name='Kategoriya')),
                ('is_active', models.BooleanField(default=True, help_text="FAQ faol yoki yo'qligi", verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ko'rsatish tartibi", verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQlar',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
