# Generated by Django 5.1.4 on 2025-09-16 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Asosiy sarlavha', max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(help_text='Kichik sarlavha yoki gradient qismi', max_length=200, verbose_name='Kichik sarlavha')),
                ('description', models.TextField(help_text='Asosiy tavsif matni', verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, help_text="Sahifa faol yoki yo'qligi", verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Biz haqimizda sahifasi',
                'verbose_name_plural': 'Biz haqimizda sahifalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Mиссия bo'limi sarlavhasi", max_length=200, verbose_name='Mиссия sarlavhasi')),
                ('description', models.TextField(help_text="Mиссия bo'limi tavsifi", verbose_name='Mиссия tavsifi')),
                ('achievement_number', models.CharField(help_text="Ko'rsatiladigan yutuq raqami (masalan: 100+)", max_length=50, verbose_name='Yutuq raqami')),
                ('achievement_text', models.CharField(help_text="Yutuq raqami qo'shilgan matn", max_length=200, verbose_name='Yutuq matni')),
                ('is_active', models.BooleanField(default=True, help_text="Mиссия faol yoki yo'qligi", verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ko'rsatish tartibi", verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Mиссия',
                'verbose_name_plural': 'Mиссияlar',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Qiymat sarlavhasi', max_length=100, verbose_name='Qiymat sarlavhasi')),
                ('description', models.TextField(help_text='Qiymat tavsifi', verbose_name='Qiymat tavsifi')),
                ('icon_svg', models.TextField(blank=True, help_text='SVG icon kodi', null=True, verbose_name='Icon SVG')),
                ('is_active', models.BooleanField(default=True, help_text="Qiymat faol yoki yo'qligi", verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ko'rsatish tartibi", verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Qiymat',
                'verbose_name_plural': 'Qiymatlar',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Mиссия punkti matni', max_length=200, verbose_name='Matn')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ko'rsatish tartibi", verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, help_text="Punkt faol yoki yo'qligi", verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='website.mission', verbose_name='Mиссия')),
            ],
            options={
                'verbose_name': 'Mиссия punkti',
                'verbose_name_plural': 'Mиссия punktlari',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
