# Generated by Django 5.1.4 on 2025-09-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_aboutpage_mission_value_missionpoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Страница о нас', 'verbose_name_plural': 'Страницы о нас'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Миссия', 'verbose_name_plural': 'Миссии'},
        ),
        migrations.AlterModelOptions(
            name='missionpoint',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Пункт миссии', 'verbose_name_plural': 'Пункты миссии'},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Ценность', 'verbose_name_plural': 'Ценности'},
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='description',
            field=models.TextField(help_text='Основной текст описания', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активна ли страница', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='subtitle',
            field=models.CharField(help_text='Подзаголовок или градиентная часть', max_length=200, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(help_text='Основной заголовок', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='achievement_number',
            field=models.CharField(help_text='Отображаемый номер достижения (например: 100+)', max_length=50, verbose_name='Номер достижения'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='achievement_text',
            field=models.CharField(help_text='Текст с номером достижения', max_length=200, verbose_name='Текст достижения'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(help_text='Описание раздела миссии', verbose_name='Описание миссии'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активна ли миссия', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(help_text='Заголовок раздела миссии', max_length=200, verbose_name='Заголовок миссии'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='missionpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='missionpoint',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активен ли пункт', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='missionpoint',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='website.mission', verbose_name='Миссия'),
        ),
        migrations.AlterField(
            model_name='missionpoint',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='missionpoint',
            name='text',
            field=models.CharField(help_text='Текст пункта миссии', max_length=200, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='value',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='value',
            name='description',
            field=models.TextField(help_text='Описание ценности', verbose_name='Описание ценности'),
        ),
        migrations.AlterField(
            model_name='value',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Код SVG иконки', null=True, verbose_name='Иконка SVG'),
        ),
        migrations.AlterField(
            model_name='value',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активна ли ценность', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='value',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='value',
            name='title',
            field=models.CharField(help_text='Заголовок ценности', max_length=100, verbose_name='Заголовок ценности'),
        ),
        migrations.AlterField(
            model_name='value',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
