# Generated by Django 5.2.6 on 2025-09-16 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_aboutpage_options_alter_mission_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='description',
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='subtitle',
            field=models.CharField(help_text='Подзаголовок под заголовком', max_length=200, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(help_text='Основной заголовок страницы', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Заголовок секции (может содержать HTML теги)', verbose_name='Заголовок секции')),
                ('description', models.TextField(help_text='Описание секции', verbose_name='Описание секции')),
                ('image', models.ImageField(blank=True, help_text='Изображение для секции', null=True, upload_to='about/sections/', verbose_name='Изображение')),
                ('button_text', models.CharField(blank=True, help_text='Текст кнопки (если есть)', max_length=100, null=True, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(blank=True, help_text='Ссылка кнопки', null=True, verbose_name='Ссылка кнопки')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли секция', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.aboutpage', verbose_name='Страница о нас')),
            ],
            options={
                'verbose_name': 'Секция о нас',
                'verbose_name_plural': 'Секции о нас',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
