# Generated by Django 5.2.6 on 2025-09-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_aboutpage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='about_page',
        ),
        migrations.RemoveField(
            model_name='missionpoint',
            name='mission',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='button_url',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='keywords',
            field=models.CharField(default=1, help_text='Слова которые будут выделены золотым цветом (через запятую)', max_length=200, verbose_name='Ключевые слова'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='description',
            field=models.TextField(help_text='Описание секции', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(default=1, help_text='Изображение для секции', upload_to='about/sections/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.TextField(help_text='Заголовок секции (может содержать HTML теги)', verbose_name='Заголовок'),
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='MissionPoint',
        ),
    ]
