# Generated by Django 5.1.4 on 2025-09-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_aboutsection_about_page_and_more'),
    ]

    operations = [
    ]
