# Generated by Django 5.1.4 on 2025-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20250916_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='button_text',
            field=models.CharField(blank=True, help_text='Текст кнопки (если есть)', max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='button_url',
            field=models.URLField(blank=True, help_text='Ссылка кнопки', null=True, verbose_name='Ссылка кнопки'),
        ),
    ]
