# Generated by Django 5.1.4 on 2025-09-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_aboutsection_button_text_aboutsection_button_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок блога', max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Описание блога', verbose_name='Описание')),
                ('image', models.ImageField(help_text='Изображение для блога', upload_to='blog/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли блог', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['-created_at'],
            },
        ),
    ]
