# Generated by Django 5.1.4 on 2025-09-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(help_text='FAQ ответ', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(blank=True, help_text='FAQ категория', max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активен ли FAQ', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(help_text='FAQ вопрос', max_length=500, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
