# Generated by Django 5.2.6 on 2025-09-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_faq_options_alter_faq_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Имя пользователя', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Фамилия пользователя', max_length=150, verbose_name='Фамилия')),
                ('email', models.EmailField(help_text='Email адрес пользователя', max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(help_text='Номер телефона пользователя', max_length=20, verbose_name='Номер телефона')),
                ('promo_code', models.CharField(help_text='Уникальный промокод', max_length=20, unique=True, verbose_name='Промокод')),
                ('referral_link', models.URLField(help_text='Уникальная реферальная ссылка', verbose_name='Реферальная ссылка')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли промокод', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Реферальная заявка',
                'verbose_name_plural': 'Реферальные заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
