# Generated by Django 5.2.6 on 2025-09-19 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_referralrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralrequest',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='Кто пригласил этого пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.referralrequest', verbose_name='Приглашен пользователем'),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='referred_by_email',
            field=models.EmailField(blank=True, help_text='Email того, кто пригласил', max_length=254, null=True, verbose_name='Email пригласившего'),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='referred_by_name',
            field=models.CharField(blank=True, help_text='Имя и фамилия того, кто пригласил', max_length=300, null=True, verbose_name='Имя пригласившего'),
        ),
    ]
