# Generated by Django 5.1.4 on 2025-09-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_referralrequest_referred_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название документа', max_length=200, verbose_name='Название документа')),
                ('description', models.TextField(blank=True, help_text='Описание документа', null=True, verbose_name='Описание')),
                ('file', models.FileField(help_text='Файл документа', upload_to='documents/', verbose_name='Файл')),
                ('file_type', models.CharField(blank=True, help_text='Тип файла (PDF, DOC, etc.)', max_length=10, null=True, verbose_name='Тип файла')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Размер файла в байтах', null=True, verbose_name='Размер файла (байт)')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Количество скачиваний файла', verbose_name='Количество скачиваний')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли документ', verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
