# Generated by Django 5.2.6 on 2025-09-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountForReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название скидки (например: Реферальная скидка)', max_length=100, verbose_name='Название')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Процент скидки (например: 6.00 для 6%)', max_digits=5, verbose_name='Процент скидки')),
                ('description', models.TextField(blank=True, help_text='Описание скидки', null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли скидка', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Скидка для рефералов',
                'verbose_name_plural': '6. Скидки для рефералов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'О нас', 'verbose_name_plural': '2. О нас'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Блог', 'verbose_name_plural': '3. Блоги'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Документ', 'verbose_name_plural': '4. Документы'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'FAQ', 'verbose_name_plural': '1. FAQ'},
        ),
        migrations.AlterModelOptions(
            name='referralrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Реферальная заявка', 'verbose_name_plural': '5. Реферальные заявки'},
        ),
    ]
