# Generated by Django 5.2.6 on 2025-09-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_discountforreferral_alter_aboutsection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountforreferral',
            options={'verbose_name': 'Скидка для рефералов', 'verbose_name_plural': '6. Скидки для рефералов'},
        ),
        migrations.RemoveField(
            model_name='discountforreferral',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='discountforreferral',
            name='description',
        ),
        migrations.RemoveField(
            model_name='discountforreferral',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='discountforreferral',
            name='name',
        ),
        migrations.RemoveField(
            model_name='discountforreferral',
            name='updated_at',
        ),
    ]
