# Generated by Django 5.1.4 on 2025-09-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_discountforreferral_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderImage1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название первого изображения', max_length=200, verbose_name='Название изображения')),
                ('description', models.TextField(blank=True, help_text='Описание изображения', null=True, verbose_name='Описание')),
                ('image', models.ImageField(help_text='Первое изображение для заголовка', upload_to='header_images/image1/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, help_text='Альтернативный текст для изображения', max_length=200, null=True, verbose_name='Альтернативный текст')),
                ('is_active', models.BooleanField(default=True, help_text='Активно ли изображение', verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Изображение заголовка 1',
                'verbose_name_plural': '8. Изображения заголовка 1',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeaderImage2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название второго изображения', max_length=200, verbose_name='Название изображения')),
                ('description', models.TextField(blank=True, help_text='Описание изображения', null=True, verbose_name='Описание')),
                ('image', models.ImageField(help_text='Второе изображение для заголовка', upload_to='header_images/image2/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, help_text='Альтернативный текст для изображения', max_length=200, null=True, verbose_name='Альтернативный текст')),
                ('is_active', models.BooleanField(default=True, help_text='Активно ли изображение', verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Изображение заголовка 2',
                'verbose_name_plural': '9. Изображения заголовка 2',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MainHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Основной заголовок главной страницы', max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, help_text='Подзаголовок главной страницы', max_length=200, null=True, verbose_name='Подзаголовок')),
                ('keywords', models.CharField(help_text='Слова которые будут выделены золотым цветом (через запятую)', max_length=200, verbose_name='Ключевые слова')),
                ('description', models.TextField(blank=True, help_text='Описание главной страницы', null=True, verbose_name='Описание')),
                ('button_text', models.CharField(blank=True, help_text='Текст кнопки', max_length=100, null=True, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(blank=True, help_text='Ссылка кнопки', null=True, verbose_name='Ссылка кнопки')),
                ('image', models.ImageField(help_text='Изображение для главного заголовка', upload_to='main_header/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли заголовок', verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Главный заголовок',
                'verbose_name_plural': '7. Главные заголовки',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
