# Generated by Django 5.1.4 on 2025-09-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_headerimage1_headerimage2_mainheader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderImage1',
        ),
        migrations.DeleteModel(
            name='HeaderImage2',
        ),
        migrations.AlterModelOptions(
            name='mainheader',
            options={'ordering': ['created_at'], 'verbose_name': 'Главный заголовок', 'verbose_name_plural': '7. Главные заголовки'},
        ),
        migrations.RemoveField(
            model_name='mainheader',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='mainheader',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='mainheader',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mainheader',
            name='order',
        ),
        migrations.RemoveField(
            model_name='mainheader',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='mainheader',
            name='video',
            field=models.FileField(blank=True, help_text='Видео для главного заголовка', null=True, upload_to='main_header/videos/', verbose_name='Видео'),
        ),
    ]
