# Generated by Django 5.1.4 on 2025-09-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_delete_headerimage1_delete_headerimage2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Заголовок шага (может содержать HTML теги)', verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Описание шага', verbose_name='Описание')),
                ('keywords', models.CharField(help_text='Слова которые будут выделены золотым цветом (через запятую)', max_length=200, verbose_name='Ключевые слова')),
                ('image', models.ImageField(help_text='Изображение для шага', upload_to='referral/steps/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли шаг', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Шаг реферальной программы',
                'verbose_name_plural': '8. Шаги реферальной программы',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
