# Generated by Django 5.1.4 on 2025-09-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_referralstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainheader',
            name='privacy_policy_file',
            field=models.FileField(blank=True, help_text='PDF файл политики конфиденциальности для скачивания', null=True, upload_to='main_header/privacy_policy/', verbose_name='Файл политики конфиденциальности'),
        ),
    ]
