# Generated by Django 5.1.4 on 2025-09-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_mainheader_privacy_policy_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок страницы контактов', max_length=200, verbose_name='Заголовок')),
                ('map_iframe', models.TextField(help_text='HTML код iframe для карты (Яндекс, Google Maps и т.д.)', verbose_name='Iframe карты')),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли страница контактов', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Страница контактов',
                'verbose_name_plural': '9. Страницы контактов',
                'ordering': ['created_at'],
            },
        ),
    ]
