# Generated by Django 5.2.6 on 2025-09-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainheader',
            name='image_banner_video',
            field=models.ImageField(default=1, help_text='Изображение для баннера видео', upload_to='main_header/', verbose_name='Изображение для баннера видео'),
            preserve_default=False,
        ),
    ]
