# Generated by Django 5.1.4 on 2025-09-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_mainheader_image_banner_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название услуги', max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(help_text='Описание услуги', verbose_name='Описание')),
                ('image', models.ImageField(help_text='Изображение для услуги', upload_to='services/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли услуга', verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': '10. Услуги',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
